Repository The-survivor-is-strong/sinabro-js, pull requests merged in 2025-02, with the labels that each got.

#10 HaEunCho248 : [시나브로 1주차] 번들러 비교 관련 README 파일 추가 및 블로그 링크 삽입
  조하은/1주차/README.md
Labels: Week 1

#5 Soyoon: 1주차 스터디 실습 내용 및 블로그 글 업데이트
  README.md
  정소윤/1주차/.DS_Store
  정소윤/1주차/.gitignore
  정소윤/1주차/index.html
  정소윤/1주차/package.json
  정소윤/1주차/public/vite.svg
  정소윤/1주차/src/counter.js
  정소윤/1주차/src/javascript.svg
  정소윤/1주차/src/main.js
  정소윤/1주차/src/style.css
  정소윤/1주차/yarn.lock
Labels: Week 1

#8 jhlee0409 : 1주차 블로그 글 업데이트
  이재혁/1주차/READMD.md
Labels: Week 1

#7 tty5799 : 1주차 공부한것 및 블로그 글 업데이트
  .gitignore
  윤성용/1주차/Week 1.md
  윤성용/1주차/img.png
  윤성용/1주차/img_1.png
  윤성용/1주차/img_2.png
  윤성용/1주차/img_3.png
  윤성용/1주차/img_4.png
  윤성용/1주차/index.html
  윤성용/1주차/package.json
  윤성용/1주차/public/vite.svg
  윤성용/1주차/src/counter.js
  윤성용/1주차/src/javascript.svg
  윤성용/1주차/src/main.js
  윤성용/1주차/src/module.js
  윤성용/1주차/src/module1.js
  윤성용/1주차/src/module2.js
  윤성용/1주차/src/style.css
Labels: Week 1

#12 feat: 권현지 1주차 readme update
  권현지/1주차/READMD.md
Labels: Week 1

#17 [osohyun0224] :: 2주차 스터디 내용 추가
  오소현/2주차/README.md
Labels: Week 2

#13 tty5799 : 2주차 공부한것 및 블로그 글 업데이트
  윤성용/2주차/Week 2.md
  윤성용/2주차/index.html
  윤성용/2주차/package.json
  윤성용/2주차/public/vite.svg
  윤성용/2주차/src/counter.js
  윤성용/2주차/src/javascript.svg
  윤성용/2주차/src/main.js
  윤성용/2주차/src/style.css
Labels: Week 2

#19 ✨ feat :: 서버리스 3주차
  오소현/3주차/README.md
Labels: Week 3
